### ISSUE TITLE
Document Phase 0: Azure Pass setup + portal overview

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/CognitiveServicesTutorial#20]
LabManual.md documentation for the setup process + portal overview of the pieces we'll need.

**Comment by jennifermarsman** [comment]
I got the Azure pass setup part at least.  Will need to sync with others on the other pieces.

**Comment by noodlefrenzy** [comment]
I'll take a look at cog services setup, and I think the other services are covered by other issues.
